structures:
  - label: Plugins
    folder: plugins
    collapse: true
  - label: Examples
    folder: examples
    collapse: true
  - label: Features
    folder: features
    collapse: true
  - label: Tests
    folder: tests
    collapse: true

